export type ProductCategory = "Disposable" | "Pod Device" | "Nicotine Pouches" | "E-Liquid" | "Tobacco";
export type ProductBrand = "Elfbar" | "Lost Mary" | "Caliburn" | "ZYN" | "Nasty" | "IGET" | "Yuoto" | "Velo" | "Pod Salt" | "Amber Leaf" | "Golden Virginia" | "American Spirit" | "Drum";

export interface Product {
  slug: string;
  name: string;
  brand: ProductBrand;
  category: ProductCategory;
  price: number;
  originalPrice?: number;
  puffCount?: number;
  nicotine?: string;
  battery?: string;
  charging?: string;
  capacity?: string;
  flavours: { name: string; color: string }[];
  image: string;
  inStock: boolean;
  isBestseller?: boolean;
  isNew?: boolean;
  badge?: string;
  gradient?: string;
  longDescription: string;
  metaTitle: string;
  metaDescription: string;
  excerpt: string;
  specs: Record<string, string>;
}

export const products: Product[] = [

  // ── ELFBAR ───────────────────────────────────────────────────────────────────
  {
    slug: "elfbar-600",
    name: "Elfbar 600",
    brand: "Elfbar",
    category: "Disposable",
    price: 999,
    originalPrice: 1249,
    puffCount: 600,
    nicotine: "20mg",
    image: "/products/elfbar-600.jpg",
    inStock: false,
    badge: "BEGINNER PICK",
    gradient: "linear-gradient(135deg, #ec4899 0%, #f43f5e 100%)",
    flavours: [
      { name: "Pink Grapefruit", color: "#f472b6" },
      { name: "Watermelon", color: "#ef4444" },
      { name: "Blueberry", color: "#3b82f6" },
      { name: "Strawberry Ice", color: "#f43f5e" },
      { name: "Mango", color: "#f59e0b" },
      { name: "Peach Ice", color: "#fb923c" },
      { name: "Grape", color: "#a855f7" },
    ],
    excerpt: "600 puffs · 2ml · 20mg Nicotine Salt · Perfect beginner vape",
    longDescription: "The Elfbar 600 is the perfect entry-level disposable vape for beginners in Bangalore. Compact, light, and no-fuss — just open and vape. Available in fruity flavours with a smooth nicotine salt formula.",
    metaTitle: "Elfbar 600 Disposable Vape — Buy in Bangalore | ₹999 | VapeBangalore.com",
    metaDescription: "Buy Elfbar 600 disposable vape in Bangalore at ₹999. Perfect beginner vape, 600 puffs, 7 flavours. 30-45 min delivery across 120+ areas.",
    specs: { "Puff Count": "600", "Capacity": "2ml", "Nicotine": "20mg Salt", "Activation": "Draw Activated" },
  },
  {
    slug: "elfbar-raya-d1",
    name: "Elfbar Raya D1",
    brand: "Elfbar",
    category: "Disposable",
    price: 1789,
    originalPrice: 2199,
    puffCount: 13000,
    nicotine: "20mg",
    battery: "650mAh",
    charging: "USB-C",
    capacity: "13ml",
    isBestseller: true,
    inStock: true,
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%)",
    image: "/products/raya-d1.jpg",
    flavours: [
      { name: "Watermelon Ice", color: "#ff6b9d" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Blueberry Ice", color: "#5352ed" },
      { name: "Mango Peach", color: "#ffa502" },
      { name: "Passion Fruit", color: "#eccc68" },
      { name: "Lychee Ice", color: "#ff6348" },
      { name: "Mixed Berries", color: "#7d5fff" },
    ],
    excerpt: "13,000 puffs · Mesh Coil · USB-C Rechargeable · Bestseller",
    longDescription: "The Elfbar Raya D1 is the ideal everyday vape for Bangalore users. With 13,000 puffs, a mesh coil for smooth flavour delivery, and Type-C recharging, the D1 is built for consistent daily use.",
    metaTitle: "Elfbar Raya D1 — Buy in Bangalore | 13,000 Puffs | ₹1,789 | VapeBangalore.com",
    metaDescription: "Buy Elfbar Raya D1 in Bangalore. 13,000 puffs, mesh coil, 7 flavours. 30-45 min delivery across 120+ areas. ₹1,789.",
    specs: { "Puff Count": "13,000", "Battery": "650mAh", "Capacity": "13ml", "Nicotine": "20mg Salt", "Charging": "USB-C", "Coil": "Mesh" },
  },
  {
    slug: "elfbar-moonnight-40k",
    name: "Elfbar MoonNight 40K",
    brand: "Elfbar",
    category: "Disposable",
    price: 2999,
    originalPrice: 3749,
    puffCount: 40000,
    nicotine: "20mg",
    isNew: true,
    inStock: true,
    badge: "NEW ARRIVAL",
    gradient: "linear-gradient(135deg, #312e81 0%, #7c3aed 100%)",
    image: "/products/elfbar-moonnight.png",
    flavours: [
      { name: "Full Moon Coffee", color: "#78350f" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Grape Ice", color: "#a855f7" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Peach Ice", color: "#fb923c" },
    ],
    excerpt: "40,000 puffs · Animated Moon Display · Dual Mesh · Coffee flavour",
    longDescription: "The Elfbar MoonNight is a statement device — 40,000 puffs with a stunning animated moon display and Coffee as a standout flavour. The dual mesh coil delivers rich, full-bodied clouds.",
    metaTitle: "Elfbar MoonNight 40K — Buy in Bangalore | 40,000 Puffs | VapeBangalore.com",
    metaDescription: "Buy Elfbar MoonNight 40K in Bangalore. 40,000 puffs, animated moon display, dual mesh. 30-45 min delivery. ₹2,999.",
    specs: { "Puff Count": "40,000", "Coil": "Dual Mesh", "Nicotine": "20mg Salt", "Charging": "USB-C", "Display": "Animated Moon" },
  },
  {
    slug: "elfbar-raya-d3",
    name: "Elfbar Raya D3",
    brand: "Elfbar",
    category: "Disposable",
    price: 2799,
    originalPrice: 3499,
    puffCount: 25000,
    nicotine: "20mg",
    isBestseller: true,
    inStock: true,
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #a855f7 0%, #6366f1 100%)",
    image: "/products/raya-d3.jpg",
    flavours: [
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Blueberry Raspberry", color: "#3b82f6" },
      { name: "Peach Mango Watermelon", color: "#f59e0b" },
      { name: "Strawberry Ice", color: "#f43f5e" },
      { name: "Kiwi Passion Fruit", color: "#84cc16" },
      { name: "Grape Ice", color: "#a855f7" },
      { name: "Lemon Mint", color: "#fde047" },
    ],
    excerpt: "25,000 puffs · Triple Mesh Coil · Smart Display · 3 Power Modes",
    longDescription: "The Elfbar Raya D3 is our bestselling vape in Bangalore. With 25,000 puffs, a smart display showing battery and puff count, and 3 adjustable power modes, the D3 gives you complete control.",
    metaTitle: "Elfbar Raya D3 — Buy in Bangalore | 25,000 Puffs | ₹2,799 | VapeBangalore.com",
    metaDescription: "Buy Elfbar Raya D3 in Bangalore. 25,000 puffs, smart display, triple mesh coil. 30-45 min delivery. ₹2,799.",
    specs: { "Puff Count": "25,000", "Coil": "Triple Mesh", "Display": "Smart LED", "Power Modes": "3", "Nicotine": "20mg Salt", "Charging": "USB-C" },
  },
  {
    slug: "elfbar-d3-pro",
    name: "Elfbar D3 Pro",
    brand: "Elfbar",
    category: "Disposable",
    price: 2999,
    originalPrice: 3749,
    puffCount: 30000,
    nicotine: "20mg",
    inStock: true,
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)",
    image: "/products/d3-pro.jpg",
    flavours: [
      { name: "Blackcurrant Ice", color: "#7c3aed" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Strawberry Banana", color: "#f43f5e" },
      { name: "Grape Honeydew", color: "#a855f7" },
      { name: "Cool Mint", color: "#06b6d4" },
    ],
    excerpt: "30,000 puffs · Turbo Mode · Adjustable Airflow · Smart Display",
    longDescription: "The Elfbar D3 Pro pushes performance with 30,000 puffs, turbo mode for bigger clouds, and adjustable airflow. The smart display keeps you updated on battery and puff count.",
    metaTitle: "Elfbar D3 Pro — Buy in Bangalore | 30,000 Puffs | ₹2,999 | VapeBangalore.com",
    metaDescription: "Buy Elfbar D3 Pro in Bangalore. 30,000 puffs, turbo mode, adjustable airflow. 30-45 min delivery. ₹2,999.",
    specs: { "Puff Count": "30,000", "Coil": "Dual Mesh", "Mode": "Turbo", "Airflow": "Adjustable", "Nicotine": "20mg Salt", "Charging": "USB-C" },
  },
  {
    slug: "elfbar-ice-king",
    name: "Elfbar Ice King",
    brand: "Elfbar",
    category: "Disposable",
    price: 2999,
    originalPrice: 3749,
    puffCount: 30000,
    nicotine: "20mg",
    battery: "850mAh",
    inStock: true,
    badge: "ONLY FEW LEFT",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)",
    image: "/products/ice-king.jpg",
    flavours: [
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Strawberry Ice", color: "#f43f5e" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Grape Ice", color: "#a855f7" },
      { name: "Lychee Ice", color: "#fb923c" },
    ],
    excerpt: "30,000 puffs · 5-Level Coolness Control · 850mAh · Menthol lovers",
    longDescription: "The Elfbar Ice King is built for menthol lovers in Bangalore. With 5 levels of adjustable coolness, you control exactly how icy each puff feels. 30,000 puffs and an 850mAh battery.",
    metaTitle: "Elfbar Ice King — Buy in Bangalore | 30,000 Puffs | ₹2,999 | VapeBangalore.com",
    metaDescription: "Buy Elfbar Ice King in Bangalore. 30,000 puffs, 5-level coolness, watermelon ice. Best menthol vape. 30-45 min delivery. ₹2,999.",
    specs: { "Puff Count": "30,000", "Battery": "850mAh", "Coolness Levels": "5", "Nicotine": "20mg Salt", "Charging": "USB-C" },
  },
  {
    slug: "elfbar-bc-10000",
    name: "Elfbar BC 10000",
    brand: "Elfbar",
    category: "Disposable",
    price: 1999,
    originalPrice: 2499,
    puffCount: 10000,
    nicotine: "20mg",
    inStock: false,
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #10b981 0%, #06b6d4 100%)",
    image: "/products/bc10000-v2.png",
    flavours: [
      { name: "Blueberry Mint", color: "#3b82f6" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Strawberry Mango", color: "#f43f5e" },
      { name: "Kiwi Passion Fruit", color: "#84cc16" },
      { name: "Peach Mango", color: "#fb923c" },
      { name: "Grape Ice", color: "#a855f7" },
      { name: "Cool Mint", color: "#06b6d4" },
    ],
    excerpt: "10,000 puffs · Transparent body · Mesh Coil · USB-C",
    longDescription: "The Elfbar BC 10000 combines elegant design with serious performance. 10,000 puffs in a sleek transparent body that shows the e-liquid level. Popular across south Bangalore.",
    metaTitle: "Elfbar BC 10000 — Buy in Bangalore | 10,000 Puffs | ₹1,999 | VapeBangalore.com",
    metaDescription: "Buy Elfbar BC 10000 in Bangalore. 10,000 puffs, transparent design, mesh coil. 30-45 min delivery. ₹1,999.",
    specs: { "Puff Count": "10,000", "Body": "Transparent", "Coil": "Mesh", "Nicotine": "20mg Salt", "Charging": "USB-C" },
  },
  {
    slug: "elfbar-raya-sobo",
    name: "Elfbar Raya SOBO",
    brand: "Elfbar",
    category: "Disposable",
    price: 3199,
    originalPrice: 3999,
    puffCount: 40000,
    nicotine: "20mg",
    battery: "1100mAh",
    isNew: true,
    inStock: true,
    badge: "NEW ARRIVAL",
    gradient: "linear-gradient(135deg, #f59e0b 0%, #78350f 100%)",
    image: "/products/raya-sobo.png",
    flavours: [
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Grape Ice", color: "#a855f7" },
      { name: "Lychee Ice", color: "#fb923c" },
      { name: "Peach Mango", color: "#fbbf24" },
    ],
    excerpt: "40,000 puffs · Interactive Game Display · 1100mAh · 5-day battery",
    longDescription: "The Elfbar Raya SOBO is the most advanced Elfbar ever available in Bangalore. 40,000 puffs, an interactive game display, dual mesh coil, and a massive 1100mAh battery lasting up to 5 days.",
    metaTitle: "Elfbar Raya SOBO — Buy in Bangalore | 40,000 Puffs | ₹3,199 | VapeBangalore.com",
    metaDescription: "Buy Elfbar Raya SOBO in Bangalore. 40,000 puffs, interactive display, 5-day battery. 30-45 min delivery. ₹3,199.",
    specs: { "Puff Count": "40,000", "Battery": "1100mAh", "Battery Life": "Up to 5 days", "Coil": "Dual Mesh", "Display": "Interactive Game" },
  },
  {
    slug: "elfbar-trio",
    name: "Elfbar Trio",
    brand: "Elfbar",
    category: "Disposable",
    price: 3099,
    originalPrice: 3874,
    puffCount: 30000,
    nicotine: "20mg",
    isNew: true,
    inStock: true,
    badge: "NEW ARRIVAL",
    gradient: "linear-gradient(135deg, #6366f1 0%, #ec4899 100%)",
    image: "/products/elfbar-trio.png",
    flavours: [
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Grape Ice", color: "#a855f7" },
      { name: "Peach Ice", color: "#fb923c" },
    ],
    excerpt: "30,000 puffs · Smart Display · Nite Electronics · Dual Device",
    longDescription: "The Elfbar Trio brings a unique dual-device design to Bangalore. Smart display, Nite Electronics technology, and 30,000 puffs. Available in two colour variants.",
    metaTitle: "Elfbar Trio — Buy in Bangalore | 30,000 Puffs | ₹3,099 | VapeBangalore.com",
    metaDescription: "Buy Elfbar Trio in Bangalore. 30,000 puffs, smart display, unique dual design. 30-45 min delivery. ₹3,099.",
    specs: { "Puff Count": "30,000", "Display": "Smart", "Coil": "Dual Mesh", "Nicotine": "20mg Salt", "Charging": "USB-C" },
  },

  // ── ELFLIQ ───────────────────────────────────────────────────────────────────
  {
    slug: "elfliq-nic-salts",
    name: "Elfliq Nic Salts",
    brand: "Elfbar",
    category: "E-Liquid",
    price: 1799,
    originalPrice: 2249,
    nicotine: "30mg",
    inStock: true,
    badge: "REFILL LIQUID",
    gradient: "linear-gradient(135deg, #d97706 0%, #92400e 100%)",
    image: "/products/elfliq-nic-salt.png",
    flavours: [
      { name: "Taro Ice Cream", color: "#a855f7" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Lemon Mint", color: "#fde047" },
    ],
    excerpt: "30mg/ml · 10ml · For Pod Systems · Powered by Elfbar",
    longDescription: "Elfliq Nic Salts are the official refill e-liquids from Elfbar. At 30mg/ml nicotine strength, they deliver a smooth, satisfying hit. The Ice King range features unique flavours like Taro Ice Cream.",
    metaTitle: "Elfliq Nic Salts — Buy in Bangalore | Elfbar Refill Liquid | VapeBangalore.com",
    metaDescription: "Buy Elfliq Nic Salts in Bangalore. Official Elfbar refill liquid, 30mg nicotine salt. Taro Ice Cream & more. 30-45 min delivery. ₹1,799.",
    specs: { "Nicotine": "30mg/ml Salt", "Volume": "10ml", "For": "Pod Systems", "Series": "Ice King" },
  },

  // ── LOST MARY ────────────────────────────────────────────────────────────────
  {
    slug: "lost-mary-mt35000-turbo",
    name: "Lost Mary MT35000 Turbo",
    brand: "Lost Mary",
    category: "Disposable",
    price: 2799,
    originalPrice: 3499,
    puffCount: 35000,
    nicotine: "20mg",
    isNew: true,
    inStock: true,
    badge: "NEW ARRIVAL",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #6366f1 100%)",
    image: "/products/lost-mary-mt35000.png",
    flavours: [
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Grape Ice", color: "#a855f7" },
      { name: "Peach Ice", color: "#fb923c" },
      { name: "Lychee Ice", color: "#fbbf24" },
    ],
    excerpt: "35,000 puffs · Turbo Mode · Smart Display · Mesh Coil",
    longDescription: "The Lost Mary MT35000 Turbo is one of the most powerful disposable vapes in Bangalore. 35,000 puffs, turbo mode for maximum vapour, and a smart display showing exact puff count and battery.",
    metaTitle: "Lost Mary MT35000 Turbo — Buy in Bangalore | 35,000 Puffs | VapeBangalore.com",
    metaDescription: "Buy Lost Mary MT35000 Turbo in Bangalore. 35,000 puffs, turbo mode, smart display. 30-45 min delivery. ₹2,799.",
    specs: { "Puff Count": "35,000", "Mode": "Turbo", "Display": "Smart", "Coil": "Mesh", "Nicotine": "20mg Salt" },
  },
  {
    slug: "lost-mary-mo10000",
    name: "Lost Mary MO10000",
    brand: "Lost Mary",
    category: "Disposable",
    price: 1999,
    originalPrice: 2499,
    puffCount: 10000,
    nicotine: "18mg",
    isBestseller: true,
    inStock: true,
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #ef4444 0%, #a855f7 100%)",
    image: "/products/lost-mary-mo10000.png",
    flavours: [
      { name: "Strawberry Grapefruit", color: "#f43f5e" },
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Strawberry Kiwi", color: "#84cc16" },
      { name: "Grape Ice", color: "#a855f7" },
    ],
    excerpt: "10,000 puffs · Mesh Coil · 18mg Nicotine · Bold flavours",
    longDescription: "The Lost Mary MO10000 delivers 10,000 puffs of consistently smooth flavour. Available in bold, vibrant colours with matching fruity flavours. A popular choice among Bangalore vapers.",
    metaTitle: "Lost Mary MO10000 — Buy in Bangalore | 10,000 Puffs | ₹1,999 | VapeBangalore.com",
    metaDescription: "Buy Lost Mary MO10000 in Bangalore. 10,000 puffs, mesh coil, 18mg nicotine. 30-45 min delivery. ₹1,999.",
    specs: { "Puff Count": "10,000", "Coil": "Mesh", "Nicotine": "18mg Salt", "Charging": "USB-C" },
  },

  // ── NASTY ────────────────────────────────────────────────────────────────────
  {
    slug: "nasty-bolt-wtf-50k",
    name: "Nasty Bolt WTF 50K",
    brand: "Nasty",
    category: "Disposable",
    price: 3499,
    originalPrice: 4374,
    puffCount: 50000,
    nicotine: "20mg",
    inStock: true,
    badge: "MOST POWERFUL",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #eab308 100%)",
    image: "/products/nasty-bolt.png",
    flavours: [
      { name: "Grape Ice", color: "#a855f7" },
      { name: "Blue Razz Lemonade", color: "#3b82f6" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Peach Ice", color: "#fb923c" },
      { name: "Lychee Ice", color: "#fbbf24" },
    ],
    excerpt: "50,000 puffs · 26ml · Dual Screen · Airflow Control · Fast Charge",
    longDescription: "The Nasty Bolt WTF is the highest puff-count vape in Bangalore — 50,000 puffs with 26ml of e-liquid. Extra fast charging in under 25 minutes, airflow control, dual screens, and 3-mode selection.",
    metaTitle: "Nasty Bolt WTF 50K — Buy in Bangalore | 50,000 Puffs | ₹3,499 | VapeBangalore.com",
    metaDescription: "Buy Nasty Bolt WTF in Bangalore. 50,000 puffs, 26ml, dual screen, airflow control. Most powerful vape. ₹3,499.",
    specs: { "Puff Count": "50,000", "Capacity": "26ml", "Fast Charge": "<25 min", "Battery": "1000mAh", "Coil": "Double Mesh" },
  },

  // ── IGET ─────────────────────────────────────────────────────────────────────
  {
    slug: "iget-astro-b18000",
    name: "IGET Astro B18000",
    brand: "IGET",
    category: "Disposable",
    price: 2399,
    originalPrice: 2999,
    puffCount: 18000,
    nicotine: "20mg",
    inStock: true,
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #7dd3fc 0%, #6366f1 100%)",
    image: "/products/iget-astro.png",
    flavours: [
      { name: "Blueberry Watermelon", color: "#3b82f6" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Peach Ice", color: "#fb923c" },
      { name: "Grape Ice", color: "#a855f7" },
      { name: "Lemon Mint", color: "#fde047" },
    ],
    excerpt: "18,000 puffs · 13 Flavours · Dual Mesh Coil · USB-C",
    longDescription: "The IGET Astro B18000 brings 18,000 puffs and 13 incredible flavours to Bangalore. Dual mesh coil for consistent flavour and a large capacity battery.",
    metaTitle: "IGET Astro B18000 — Buy in Bangalore | 18,000 Puffs | ₹2,399 | VapeBangalore.com",
    metaDescription: "Buy IGET Astro B18000 in Bangalore. 18,000 puffs, 13 flavours, dual mesh coil. 30-45 min delivery. ₹2,399.",
    specs: { "Puff Count": "18,000", "Flavours": "13", "Coil": "Dual Mesh", "Nicotine": "20mg Salt", "Charging": "USB-C" },
  },

  // ── YUOTO ────────────────────────────────────────────────────────────────────
  {
    slug: "yuoto-beyonder",
    name: "Yuoto Beyonder",
    brand: "Yuoto",
    category: "Disposable",
    price: 1999,
    originalPrice: 2499,
    puffCount: 7000,
    nicotine: "20mg",
    inStock: true,
    badge: "GOOD VALUE",
    gradient: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    image: "/products/yuoto-beyonder.png",
    flavours: [
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Grape Ice", color: "#a855f7" },
      { name: "Peach Ice", color: "#fb923c" },
    ],
    excerpt: "7,000 puffs · Compact · USB-C · Good value",
    longDescription: "The Yuoto Beyonder is a solid mid-range disposable vape for Bangalore. 7,000 puffs in a compact, pocket-friendly form factor. Great option between entry-level and premium.",
    metaTitle: "Yuoto Beyonder — Buy in Bangalore | 7,000 Puffs | ₹1,999 | VapeBangalore.com",
    metaDescription: "Buy Yuoto Beyonder in Bangalore. 7,000 puffs, watermelon ice, compact design. 30-45 min delivery. ₹1,999.",
    specs: { "Puff Count": "7,000", "Nicotine": "20mg Salt", "Charging": "USB-C", "Activation": "Draw Activated" },
  },
  {
    slug: "yuoto-thanos",
    name: "Yuoto Thanos",
    brand: "Yuoto",
    category: "Disposable",
    price: 1799,
    originalPrice: 2249,
    puffCount: 5000,
    nicotine: "20mg",
    isNew: true,
    inStock: true,
    badge: "NEW",
    gradient: "linear-gradient(135deg, #22c55e 0%, #16a34a 100%)",
    image: "/products/yuoto-thanos.png",
    flavours: [
      { name: "Mint Ice", color: "#06b6d4" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Grape Ice", color: "#a855f7" },
    ],
    excerpt: "5,000 puffs · Mint Ice · Compact · USB-C",
    longDescription: "The Yuoto Thanos is a powerful 5,000 puff disposable vape for Bangalore. Compact yet powerful, delivering smooth mint ice hits with consistent flavour throughout.",
    metaTitle: "Yuoto Thanos — Buy in Bangalore | 5,000 Puffs | ₹1,799 | VapeBangalore.com",
    metaDescription: "Buy Yuoto Thanos in Bangalore. 5,000 puffs, mint ice, compact design. 30-45 min delivery. ₹1,799.",
    specs: { "Puff Count": "5,000", "Nicotine": "20mg Salt", "Charging": "USB-C", "Activation": "Draw Activated" },
  },

  // ── POD SALT ─────────────────────────────────────────────────────────────────
  {
    slug: "pod-salt-hit-the-spot",
    name: "Pod Salt Hit The Spot",
    brand: "Pod Salt",
    category: "Disposable",
    price: 1799,
    originalPrice: 2249,
    puffCount: 35000,
    nicotine: "20mg",
    isNew: true,
    inStock: true,
    badge: "NEW ARRIVAL",
    gradient: "linear-gradient(135deg, #ec4899 0%, #f97316 100%)",
    image: "/products/pod-salt-disposable.png",
    flavours: [
      { name: "Mixed Berry", color: "#a855f7" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Watermelon Ice", color: "#ef4444" },
      { name: "Blueberry Ice", color: "#3b82f6" },
      { name: "Peach Mango", color: "#fb923c" },
      { name: "Grape Ice", color: "#7c3aed" },
    ],
    excerpt: "35,000 puffs · Battery Display · USB-C · Multiple Flavours",
    longDescription: "The Pod Salt Hit The Spot is one of the highest puff-count devices in Bangalore. 35,000 puffs, battery display, and rich fruity flavour profiles.",
    metaTitle: "Pod Salt Hit The Spot — Buy in Bangalore | 35,000 Puffs | VapeBangalore.com",
    metaDescription: "Buy Pod Salt Hit The Spot in Bangalore. 35,000 puffs, battery display, fruity flavours. 30-45 min delivery. ₹1,799.",
    specs: { "Puff Count": "35,000", "Display": "Battery", "Nicotine": "20mg Salt", "Charging": "USB-C" },
  },
  {
    slug: "pod-salt-core-nic-salt",
    name: "Pod Salt Core Nic Salt",
    brand: "Pod Salt",
    category: "E-Liquid",
    price: 1599,
    originalPrice: 1999,
    nicotine: "20mg",
    inStock: true,
    badge: "REFILL LIQUID",
    gradient: "linear-gradient(135deg, #84cc16 0%, #ca8a04 100%)",
    image: "/products/pod-salt-core.png",
    flavours: [
      { name: "Lemon & Lime Ice", color: "#fde047" },
      { name: "Mixed Berry", color: "#a855f7" },
      { name: "Mango Ice", color: "#f59e0b" },
      { name: "Strawberry Kiwi", color: "#f43f5e" },
      { name: "Watermelon", color: "#ef4444" },
      { name: "Blueberry", color: "#3b82f6" },
    ],
    excerpt: "20mg/ml · 10ml · For Pod Systems · Lemon & Lime Ice",
    longDescription: "Pod Salt Core is a premium nicotine salt e-liquid for Bangalore. The Lemon & Lime Ice flavour is a citrusy, refreshing blend with a cool menthol finish — one of the most popular refill liquids.",
    metaTitle: "Pod Salt Core Nic Salt — Buy in Bangalore | Refill Liquid | VapeBangalore.com",
    metaDescription: "Buy Pod Salt Core nicotine salt e-liquid in Bangalore. Lemon & Lime Ice, 20mg nicotine salt. 30-45 min delivery. ₹1,599.",
    specs: { "Nicotine": "20mg/ml Salt", "Volume": "10ml", "For": "Pod Systems" },
  },

  // ── ZYN ──────────────────────────────────────────────────────────────────────
  {
    slug: "zyn-cool-mint",
    name: "ZYN Cool Mint",
    brand: "ZYN",
    category: "Nicotine Pouches",
    price: 999,
    originalPrice: 1249,
    nicotine: "6mg",
    inStock: true,
    badge: "SMOKE-FREE",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #0ea5e9 100%)",
    image: "/products/zyn-velo.png",
    flavours: [
      { name: "Cool Mint", color: "#06b6d4" },
    ],
    excerpt: "6mg · 16 Pouches · Tobacco-free · Smoke-free · Discreet",
    longDescription: "ZYN Cool Mint nicotine pouches — the smokeless, vapeless way to enjoy nicotine in Bangalore. No smoke, no vapour — just place a pouch under your lip. Perfect for offices and public spaces.",
    metaTitle: "ZYN Cool Mint Nicotine Pouches — Buy in Bangalore | ₹999 | VapeBangalore.com",
    metaDescription: "Buy ZYN Cool Mint nicotine pouches in Bangalore. Smoke-free, vapour-free. 16 pouches, 6mg nicotine. 30-45 min delivery. ₹999.",
    specs: { "Pouches": "16 per tin", "Nicotine": "6mg", "Tobacco": "Free", "Smoke": "Free", "Vapour": "Free" },
  },

  // ── VELO ─────────────────────────────────────────────────────────────────────
  {
    slug: "velo-freezing-peppermint",
    name: "Velo Freezing Peppermint",
    brand: "Velo",
    category: "Nicotine Pouches",
    price: 999,
    originalPrice: 1249,
    nicotine: "7mg",
    inStock: true,
    badge: "SMOKE-FREE",
    gradient: "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)",
    image: "/products/velo-freezing-peppermint.png",
    flavours: [
      { name: "Freezing Peppermint", color: "#3b82f6" },
    ],
    excerpt: "Intense peppermint · Tobacco-free · Smoke-free · Discreet",
    longDescription: "Velo Freezing Peppermint nicotine pouches deliver an intense, icy peppermint experience without any smoke or vapour. Discreet, clean, and refreshing.",
    metaTitle: "Velo Freezing Peppermint Pouches — Buy in Bangalore | ₹999 | VapeBangalore.com",
    metaDescription: "Buy Velo Freezing Peppermint nicotine pouches in Bangalore. Smoke-free, intense peppermint. 30-45 min delivery. ₹999.",
    specs: { "Nicotine": "7mg", "Tobacco": "Free", "Smoke": "Free", "Flavour": "Freezing Peppermint" },
  },

  // ── TOBACCO ──────────────────────────────────────────────────────────────────
  {
    slug: "amber-leaf-tobacco",
    name: "Amber Leaf Rolling Tobacco",
    brand: "Amber Leaf",
    category: "Tobacco",
    price: 999,
    originalPrice: 1299,
    inStock: true,
    badge: "TOBACCO",
    gradient: "linear-gradient(135deg, #ca8a04 0%, #78350f 100%)",
    image: "/products/amber-leaf.png",
    flavours: [{ name: "Original Blend", color: "#ca8a04" }],
    excerpt: "50g · Finest Virginia · Original Blend · Smooth and mild",
    longDescription: "Amber Leaf is one of the most popular rolling tobaccos in Bangalore. Made from finest Virginia tobacco with a smooth, balanced flavour. Available for discreet, fast delivery.",
    metaTitle: "Amber Leaf Rolling Tobacco — Buy in Bangalore | 50g | ₹999 | VapeBangalore.com",
    metaDescription: "Buy Amber Leaf rolling tobacco in Bangalore. 50g finest Virginia original blend. Discreet delivery. ₹999.",
    specs: { "Weight": "50g", "Type": "Virginia Tobacco", "Blend": "Original" },
  },
  {
    slug: "drum-bright-blue-tobacco",
    name: "Drum Bright Blue Tobacco",
    brand: "Drum",
    category: "Tobacco",
    price: 1199,
    originalPrice: 1499,
    inStock: true,
    badge: "TOBACCO",
    gradient: "linear-gradient(135deg, #3b82f6 0%, #1e40af 100%)",
    image: "/products/drum-blue.png",
    flavours: [{ name: "Bright Blue", color: "#3b82f6" }],
    excerpt: "50g · Premium Quality · Light and smooth burn",
    longDescription: "Drum Bright Blue is a premium rolling tobacco known for its smooth, consistent burn and balanced flavour. Available for fast delivery in Bangalore.",
    metaTitle: "Drum Bright Blue Rolling Tobacco — Buy in Bangalore | 50g | VapeBangalore.com",
    metaDescription: "Buy Drum Bright Blue rolling tobacco in Bangalore. 50g premium quality. Discreet delivery. ₹1,199.",
    specs: { "Weight": "50g", "Type": "Rolling Tobacco", "Blend": "Bright Blue" },
  },
  {
    slug: "golden-virginia-tobacco",
    name: "Golden Virginia Tobacco",
    brand: "Golden Virginia",
    category: "Tobacco",
    price: 1199,
    originalPrice: 1499,
    inStock: true,
    badge: "TOBACCO",
    gradient: "linear-gradient(135deg, #16a34a 0%, #ca8a04 100%)",
    image: "/products/golden-virginia.png",
    flavours: [{ name: "The Original", color: "#ca8a04" }],
    excerpt: "50g · Since 1877 · Full-bodied golden Virginia leaf",
    longDescription: "Golden Virginia — The Original since 1877 — is one of the world's most respected rolling tobaccos. Now available for delivery in Bangalore. Rich, golden Virginia leaf with a smooth, even burn.",
    metaTitle: "Golden Virginia Tobacco — Buy in Bangalore | 50g | VapeBangalore.com",
    metaDescription: "Buy Golden Virginia rolling tobacco in Bangalore. 50g original since 1877. Discreet delivery. ₹1,199.",
    specs: { "Weight": "50g", "Type": "Virginia Tobacco", "Since": "1877" },
  },
  {
    slug: "natural-american-spirit-tobacco",
    name: "Natural American Spirit",
    brand: "American Spirit",
    category: "Tobacco",
    price: 1199,
    originalPrice: 1499,
    inStock: true,
    badge: "TOBACCO",
    gradient: "linear-gradient(135deg, #0ea5e9 0%, #dc2626 100%)",
    image: "/products/american-spirit.png",
    flavours: [{ name: "Natural Blend", color: "#84cc16" }],
    excerpt: "50g · 100% Additive-Free · Whole Leaf Tobacco · Pure",
    longDescription: "Natural American Spirit is 100% additive-free whole leaf tobacco. No additives, no flavours — just pure, natural tobacco. Available for delivery in Bangalore.",
    metaTitle: "Natural American Spirit Tobacco — Buy in Bangalore | 50g | VapeBangalore.com",
    metaDescription: "Buy Natural American Spirit tobacco in Bangalore. 100% additive-free whole leaf tobacco. Discreet delivery. ₹1,199.",
    specs: { "Weight": "50g", "Additives": "None", "Type": "Whole Leaf Tobacco" },
  },

  // ── CALIBURN POD DEVICES ─────────────────────────────────────────────────────
  {
    slug: "caliburn-koko-gk3",
    name: "Caliburn KOKO GK3",
    brand: "Caliburn",
    category: "Pod Device",
    price: 6299,
    originalPrice: 7874,
    battery: "690mAh",
    charging: "USB-C",
    inStock: true,
    badge: "POD DEVICE",
    gradient: "linear-gradient(135deg, #1d4ed8 0%, #06b6d4 100%)",
    image: "/products/caliburn-koko.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "690mAh · 2ml Pod · Draw Activated · KOKO Compact Design",
    longDescription: "The Caliburn KOKO GK3 is the iconic KOKO form factor upgraded for 2024. Compact, pocket-friendly, 690mAh battery, 2ml refillable pod with Pro-FOCS flavour technology.",
    metaTitle: "Caliburn KOKO GK3 — Buy in Bangalore | Pod Device | ₹6,299 | VapeBangalore.com",
    metaDescription: "Buy Caliburn KOKO GK3 pod device in Bangalore. 690mAh, 2ml pod, draw activated. 30-45 min delivery. ₹6,299.",
    specs: { "Battery": "690mAh", "Pod": "2ml Refillable", "Activation": "Draw", "Charging": "USB-C", "Tech": "Pro-FOCS" },
  },
  {
    slug: "caliburn-g3-lite",
    name: "Caliburn G3 Lite",
    brand: "Caliburn",
    category: "Pod Device",
    price: 4599,
    originalPrice: 5749,
    battery: "750mAh",
    charging: "USB-C",
    inStock: true,
    badge: "POD DEVICE",
    gradient: "linear-gradient(135deg, #374151 0%, #b45309 100%)",
    image: "/products/caliburn-g3-lite.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "750mAh · 2.5ml · 1.2Ω Coil · Lightweight · Best budget pod",
    longDescription: "The Caliburn G3 Lite is the most affordable entry into the Caliburn G3 ecosystem. Lightweight and portable with 750mAh battery, 2.5ml refillable pod, and reliable G3 coil system.",
    metaTitle: "Caliburn G3 Lite — Buy in Bangalore | Pod Device | ₹4,599 | VapeBangalore.com",
    metaDescription: "Buy Caliburn G3 Lite pod device in Bangalore. 750mAh, 2.5ml pod, lightweight. Best budget pod device. ₹4,599.",
    specs: { "Battery": "750mAh", "Pod": "2.5ml", "Coil": "1.2Ω Mesh", "Charging": "USB-C" },
  },
  {
    slug: "caliburn-g3-lite-koko",
    name: "Caliburn G3 Lite KOKO",
    brand: "Caliburn",
    category: "Pod Device",
    price: 5999,
    originalPrice: 7499,
    battery: "750mAh",
    charging: "USB-C",
    inStock: true,
    badge: "POD DEVICE",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #10b981 100%)",
    image: "/products/caliburn-g3-lite-koko.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "750mAh · KOKO Form · G3 Coil · Graffiti Design",
    longDescription: "The Caliburn G3 Lite KOKO combines the beloved compact KOKO form factor with the G3 coil system. Bold graffiti-inspired design with G3 Lite internals.",
    metaTitle: "Caliburn G3 Lite KOKO — Buy in Bangalore | Pod Device | ₹5,999 | VapeBangalore.com",
    metaDescription: "Buy Caliburn G3 Lite KOKO pod device in Bangalore. 750mAh, KOKO design, G3 coil. 30-45 min delivery. ₹5,999.",
    specs: { "Battery": "750mAh", "Pod": "2.5ml", "Form": "KOKO Compact", "Charging": "USB-C" },
  },
  {
    slug: "caliburn-g3-pro-koko",
    name: "Caliburn G3 Pro KOKO",
    brand: "Caliburn",
    category: "Pod Device",
    price: 6999,
    originalPrice: 8749,
    battery: "900mAh",
    charging: "USB-C",
    inStock: true,
    badge: "POD DEVICE",
    gradient: "linear-gradient(135deg, #ca8a04 0%, #1f2937 100%)",
    image: "/products/caliburn-g3-pro-koko.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "900mAh · 35W · Full Colour Screen · G3 Pro Coil · KOKO",
    longDescription: "The Caliburn G3 Pro KOKO — KOKO form factor with full colour display, 35W output, 900mAh battery. The G3 Pro coil delivers rich, full-flavoured clouds.",
    metaTitle: "Caliburn G3 Pro KOKO — Buy in Bangalore | Pod Device | ₹6,999 | VapeBangalore.com",
    metaDescription: "Buy Caliburn G3 Pro KOKO in Bangalore. 35W, full colour screen, 900mAh, KOKO design. 30-45 min delivery. ₹6,999.",
    specs: { "Battery": "900mAh", "Output": "35W", "Display": "Full Colour TFT", "Form": "KOKO", "Pod": "2ml" },
  },
  {
    slug: "caliburn-g4",
    name: "Caliburn G4",
    brand: "Caliburn",
    category: "Pod Device",
    price: 7499,
    originalPrice: 9374,
    battery: "1000mAh",
    charging: "USB-C",
    inStock: true,
    badge: "FLAGSHIP",
    gradient: "linear-gradient(135deg, #d1d5db 0%, #6b7280 100%)",
    image: "/products/caliburn-g4.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "1000mAh · 35W · Animated TFT Screen · Pearl Finish · Flagship",
    longDescription: "The Caliburn G4 is a flagship pod device with stunning full-colour animated TFT display, 1000mAh battery, and 35W output. The pearl/marble body finish makes it the most visually premium pod device in Bangalore.",
    metaTitle: "Caliburn G4 — Buy in Bangalore | Pod Device | ₹7,499 | VapeBangalore.com",
    metaDescription: "Buy Caliburn G4 pod device in Bangalore. 35W, animated display, 1000mAh, pearl finish. 30-45 min delivery. ₹7,499.",
    specs: { "Battery": "1000mAh", "Output": "35W", "Display": "Animated TFT", "Coils": "0.4Ω & 0.6Ω", "Finish": "Pearl" },
  },
  {
    slug: "caliburn-g4-mini",
    name: "Caliburn G4 Mini",
    brand: "Caliburn",
    category: "Pod Device",
    price: 5499,
    originalPrice: 6874,
    battery: "750mAh",
    charging: "USB-C",
    inStock: true,
    badge: "POD DEVICE",
    gradient: "linear-gradient(135deg, #0ea5e9 0%, #2563eb 100%)",
    image: "/products/caliburn-g4-mini.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "750mAh · Slim Pen Style · Colour LED · Most portable G4",
    longDescription: "The Caliburn G4 Mini is the slim, pen-style version of the G4. 750mAh battery, colourful LED battery indicator, G4 Mini coil. The most portable pod device in the G4 lineup.",
    metaTitle: "Caliburn G4 Mini — Buy in Bangalore | Pod Device | ₹5,499 | VapeBangalore.com",
    metaDescription: "Buy Caliburn G4 Mini pod device in Bangalore. 750mAh, slim design, colour LED. 30-45 min delivery. ₹5,499.",
    specs: { "Battery": "750mAh", "Design": "Slim Pen", "Indicator": "Colour LED", "Pod": "2ml" },
  },
  {
    slug: "caliburn-g4-pro",
    name: "Caliburn G4 Pro",
    brand: "Caliburn",
    category: "Pod Device",
    price: 7199,
    originalPrice: 8999,
    battery: "1200mAh",
    charging: "USB-C",
    inStock: true,
    badge: "FLAGSHIP",
    gradient: "linear-gradient(135deg, #c0c0c0 0%, #374151 100%)",
    image: "/products/caliburn-g4-pro.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "1200mAh · 35W · Full Animated Screen · Custom Wallpapers",
    longDescription: "The Caliburn G4 Pro — slim, premium pod mod with full animated TFT screen spanning almost the entire front. 1200mAh battery, 35W output, custom animated wallpapers.",
    metaTitle: "Caliburn G4 Pro — Buy in Bangalore | Pod Device | ₹7,199 | VapeBangalore.com",
    metaDescription: "Buy Caliburn G4 Pro in Bangalore. 35W, full animated screen, 1200mAh. Most premium pod device. ₹7,199.",
    specs: { "Battery": "1200mAh", "Output": "35W", "Display": "Full Animated TFT", "Wallpapers": "Custom", "Coils": "0.4Ω & 0.6Ω" },
  },
  {
    slug: "caliburn-g4-pro-koko",
    name: "Caliburn G4 Pro KOKO",
    brand: "Caliburn",
    category: "Pod Device",
    price: 7599,
    originalPrice: 9499,
    battery: "1200mAh",
    charging: "USB-C",
    inStock: true,
    badge: "TOP OF LINE",
    gradient: "linear-gradient(135deg, #d4af37 0%, #374151 100%)",
    image: "/products/caliburn-g4-pro-koko.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "1200mAh · 35W · Full-Panel Screen · KOKO Form · Most Premium",
    longDescription: "The Caliburn G4 Pro KOKO — most premium KOKO ever made. Full-screen animated display on KOKO compact body. 1200mAh battery, 35W, custom animated wallpapers.",
    metaTitle: "Caliburn G4 Pro KOKO — Buy in Bangalore | Pod Device | ₹7,599 | VapeBangalore.com",
    metaDescription: "Buy Caliburn G4 Pro KOKO in Bangalore. 35W, full-panel screen, 1200mAh, KOKO design. Premium pod device. ₹7,599.",
    specs: { "Battery": "1200mAh", "Output": "35W", "Display": "Full-Panel Animated", "Form": "KOKO", "Wallpapers": "Custom" },
  },
  {
    slug: "caliburn-g5-lite",
    name: "Caliburn G5 Lite",
    brand: "Caliburn",
    category: "Pod Device",
    price: 5699,
    originalPrice: 7124,
    battery: "800mAh",
    charging: "USB-C",
    isNew: true,
    inStock: true,
    badge: "LATEST GEN",
    gradient: "linear-gradient(135deg, #84cc16 0%, #f97316 100%)",
    image: "/products/caliburn-g5-lite.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "800mAh · 2.5ml · G5 Coil · Wave Pattern · Latest Gen",
    longDescription: "The Caliburn G5 Lite is the latest generation slim pod device from Uwell. 800mAh battery, 2.5ml refillable pod, new G5 coil system. Wave-pattern body design in Lime and Orange.",
    metaTitle: "Caliburn G5 Lite — Buy in Bangalore | Pod Device | ₹5,699 | VapeBangalore.com",
    metaDescription: "Buy Caliburn G5 Lite pod device in Bangalore. 800mAh, G5 coil, wave design. Latest gen pod device. ₹5,699.",
    specs: { "Battery": "800mAh", "Pod": "2.5ml", "Coil": "G5 Mesh", "Design": "Wave Pattern", "Charging": "USB-C" },
  },
  {
    slug: "caliburn-g5-lite-se",
    name: "Caliburn G5 Lite SE",
    brand: "Caliburn",
    category: "Pod Device",
    price: 5999,
    originalPrice: 7499,
    battery: "800mAh",
    charging: "USB-C",
    inStock: true,
    badge: "SPECIAL EDITION",
    gradient: "linear-gradient(135deg, #f97316 0%, #b45309 100%)",
    image: "/products/caliburn-g5-lite-se.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "800mAh · Leather Texture · G5 SE Coil · Special Edition",
    longDescription: "The Caliburn G5 Lite SE — Special Edition with premium leather-texture body. Same 800mAh battery and G5 coil performance but with premium tactile grip.",
    metaTitle: "Caliburn G5 Lite SE — Buy in Bangalore | Pod Device | ₹5,999 | VapeBangalore.com",
    metaDescription: "Buy Caliburn G5 Lite SE in Bangalore. Special edition, leather texture, 800mAh. 30-45 min delivery. ₹5,999.",
    specs: { "Battery": "800mAh", "Body": "Leather Texture", "Coil": "G5 SE", "Edition": "Special" },
  },
  {
    slug: "caliburn-g5-lite-koko",
    name: "Caliburn G5 Lite KOKO",
    brand: "Caliburn",
    category: "Pod Device",
    price: 6999,
    originalPrice: 8749,
    battery: "900mAh",
    charging: "USB-C",
    isNew: true,
    inStock: true,
    badge: "LATEST KOKO",
    gradient: "linear-gradient(135deg, #2dd4bf 0%, #0ea5e9 100%)",
    image: "/products/caliburn-g5-lite-koko.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "900mAh · KOKO Compact · G5 Coil · Wave Body · Latest Gen",
    longDescription: "The Caliburn G5 Lite KOKO — latest G5 coil technology in the iconic KOKO compact body. 900mAh battery, 2ml pod, wave-pattern design on teal body.",
    metaTitle: "Caliburn G5 Lite KOKO — Buy in Bangalore | Pod Device | ₹6,999 | VapeBangalore.com",
    metaDescription: "Buy Caliburn G5 Lite KOKO in Bangalore. Latest G5 coil, 900mAh, KOKO design. 30-45 min delivery. ₹6,999.",
    specs: { "Battery": "900mAh", "Pod": "2ml", "Coil": "G5 Mesh", "Form": "KOKO Compact", "Design": "Wave Pattern" },
  },
  {
    slug: "caliburn-a2",
    name: "Caliburn A2",
    brand: "Caliburn",
    category: "Pod Device",
    price: 5899,
    originalPrice: 7374,
    battery: "520mAh",
    charging: "USB-C",
    inStock: true,
    badge: "POD DEVICE",
    gradient: "linear-gradient(135deg, #ff6b35 0%, #f7c59f 100%)",
    image: "/products/caliburn-a2.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "520mAh · 15W · Pro-FOCS Tech · Top Fill · Compact",
    longDescription: "The Uwell Caliburn A2 — sleek compact pod system for everyday vaping. 520mAh battery, 15W output, Pro-FOCS flavor technology. Available in multiple colors.",
    metaTitle: "Caliburn A2 — Buy in Bangalore | Pod Device | ₹5,899 | VapeBangalore.com",
    metaDescription: "Buy Uwell Caliburn A2 pod system in Bangalore. 520mAh battery, 15W output, Pro-FOCS technology. 30-45 min delivery. ₹5,899.",
    specs: { "Battery": "520mAh", "Output": "15W", "Tech": "Pro-FOCS", "Fill": "Top Fill", "Charging": "USB-C" },
  },
  {
    slug: "caliburn-g3-pro",
    name: "Caliburn G3 Pro",
    brand: "Caliburn",
    category: "Pod Device",
    price: 7999,
    originalPrice: 9999,
    battery: "1000mAh",
    charging: "USB-C",
    inStock: true,
    badge: "POD DEVICE",
    gradient: "linear-gradient(135deg, #2c3e50 0%, #4ca1af 100%)",
    image: "/products/caliburn-g3-pro.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "OLED Display · 5-35W · Pro-FOCS 3.0 · 1000mAh",
    longDescription: "The Uwell Caliburn G3 Pro — most advanced Caliburn with large OLED display, adjustable wattage 5-35W, and Pro-FOCS 3.0 flavor technology.",
    metaTitle: "Caliburn G3 Pro — Buy in Bangalore | Pod Device | ₹7,999 | VapeBangalore.com",
    metaDescription: "Buy Uwell Caliburn G3 Pro in Bangalore. OLED display, 35W output, Pro-FOCS 3.0. 30-45 min delivery. ₹7,999.",
    specs: { "Battery": "1000mAh", "Output": "5-35W", "Display": "OLED", "Tech": "Pro-FOCS 3.0", "Charging": "USB-C" },
  },
  {
    slug: "caliburn-gk2",
    name: "Caliburn GK2",
    brand: "Caliburn",
    category: "Pod Device",
    price: 5800,
    originalPrice: 7250,
    battery: "690mAh",
    charging: "USB-C",
    inStock: true,
    badge: "POD DEVICE",
    gradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
    image: "/products/caliburn-gk2.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "690mAh · 18W · KOKO Cyberpunk Design · Draw Activated",
    longDescription: "The Uwell Caliburn GK2 — iconic KOKO design with bold cyberpunk aesthetic. 690mAh battery, 18W output, draw-activated firing.",
    metaTitle: "Caliburn GK2 — Buy in Bangalore | Pod Device | ₹5,800 | VapeBangalore.com",
    metaDescription: "Buy Uwell Caliburn GK2 in Bangalore. Bold KOKO design, 690mAh battery, 18W output. 30-45 min delivery. ₹5,800.",
    specs: { "Battery": "690mAh", "Output": "18W", "Design": "KOKO Cyberpunk", "Activation": "Draw", "Charging": "USB-C" },
  },
  {
    slug: "caliburn-xpod",
    name: "Caliburn Xpod",
    brand: "Caliburn",
    category: "Pod Device",
    price: 6500,
    originalPrice: 8125,
    charging: "USB-C",
    inStock: true,
    badge: "POD DEVICE",
    gradient: "linear-gradient(135deg, #373b44 0%, #4286f4 100%)",
    image: "/products/caliburn-xpod.png",
    flavours: [{ name: "Use with any Nic Salt", color: "#6b7280" }],
    excerpt: "Full Colour Display · G3 Pro Tech · Premium Build",
    longDescription: "The Uwell Caliburn Xpod — premium vaping experience with large full-colour display and intelligent G3 Pro technology. Designed for vapers who want style and performance.",
    metaTitle: "Caliburn Xpod — Buy in Bangalore | Pod Device | ₹6,500 | VapeBangalore.com",
    metaDescription: "Buy Uwell Caliburn Xpod in Bangalore. Full colour display, G3 Pro technology. 30-45 min delivery. ₹6,500.",
    specs: { "Display": "Full Colour", "Tech": "G3 Pro", "Charging": "USB-C" },
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────
export const PRODUCT_COUNT = products.length;

export function getProductsByBrand(brand: string) {
  return products.filter((p) => p.brand === brand);
}

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category === category);
}

export function getRelatedProducts(slug: string, limit = 4) {
  const product = products.find((p) => p.slug === slug);
  if (!product) return products.slice(0, limit);
  return products
    .filter((p) => p.slug !== slug && (p.brand === product.brand || p.category === product.category))
    .slice(0, limit);
}

// ── Legacy helpers (used by existing components) ─────────────────────────────
export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getBestsellers(limit = 4) {
  return products.filter((p) => p.isBestseller && p.inStock).slice(0, limit);
}

export const CATEGORIES: ProductCategory[] = [
  "Disposable",
  "Pod Device",
  "Nicotine Pouches",
  "E-Liquid",
  "Tobacco",
];

export const BRANDS: ProductBrand[] = [
  "Elfbar",
  "Lost Mary",
  "Caliburn",
  "ZYN",
  "Nasty",
  "IGET",
  "Yuoto",
  "Velo",
  "Pod Salt",
  "Amber Leaf",
  "Golden Virginia",
  "American Spirit",
  "Drum",
];
